export const ADD_USER = "ADD_USER";
export const EDIT_USER = "EDIT_USER";
export const TOGGLE_USER_ACCOUNT_STATUS = "TOGGLE_USER_ACCOUNT_STATUS";
export const SET_FILTER = "SET_FILTER";
export const FETCH_USERAPI = "FETCH_USERAPI";